routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Post;


Route::get('', function () {
    $posts = Post::where('published', true)->orderBy('created_at', 'desc')->limit(3)->get();
    return view('index', compact('posts'));
});

Route::resource('projects', 'ProjectsController', ['only' => [
    'index', 'show'
]]);

Route::resource('blog', 'PostsController', ['only' => [
    'index', 'show'
]]);

Route::get('japanese', function() {
    $data = [];
    if (Storage::exists('wanikani.json')) {
        $contents = Storage::get('wanikani.json');
        $data = json_decode($contents);
    }
    return view('japanese', compact('data'));
});

Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'as' => 'admin.', 'middleware' => 'auth'], function() {
    Route::get('', 'HomeController@index');
    Route::resource('projects', 'ProjectsController');
    Route::resource('posts', 'PostsController');
});

Auth::routes();

app/Project.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Project extends Model
{

    public $fillable = [
        'title',
        'slug',
        'md_body',
        'image',
    ];

}

app/Http/Controllers/Admin/ProjectsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Project;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use GrahamCampbell\Markdown\Facades\Markdown;

class ProjectsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $projects = Project::all();

        return view('admin.projects.index', compact('projects'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $project = new Project;

        return view('admin.projects.index', compact('project'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        return redirect(route('admin.projects.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Project  $project
     * @return \Illuminate\Http\Response
     */
    public function show(Project $project)
    {
        return redirect(route('admin.projects.edit', $project));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Project  $project
     * @return \Illuminate\Http\Response
     */
    public function edit(Project $project)
    {
        return view('admin.projects.edit', compact('project'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Project  $project
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Project $project)
    {
        $project->update(request([
            'title',
            'slug',
            'md_body',
            'image',
        ]));

        $project->body = Markdown::convertToHtml($project->md_body);

        if ($project->save()) {
            return redirect(route('admin.projects.index'));
        } else {
            return view('admin.projects.edit', $project);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Project  $project
     * @return \Illuminate\Http\Response
     */
    public function destroy(Project $project)
    {
        $project->delete();
        return redirect(route('admin.projects.index'));
    }
}

app/Http/Controllers/ProjectsController.php
<?php

namespace App\Http\Controllers;

use App\Project;
use Illuminate\Http\Request;

class ProjectsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
		$projects = Project::all();
		return view('projects.index', compact('projects'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Project  $project
     * @return \Illuminate\Http\Response
     */
    public function show($slug)
    {
        $project = Project::where('slug', $slug)->first();
        if ($project) {
            return view('projects.show', compact('project'));
        } else {
            abort(404);
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Project  $project
     * @return \Illuminate\Http\Response
     */
    public function edit(Project $project)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Project  $project
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Project $project)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Project  $project
     * @return \Illuminate\Http\Response
     */
    public function destroy(Project $project)
    {
        //
    }
}

resources/views/admin/projects/_fields.blade.php
{{ csrf_field() }}

<label for="title">Title</label><br>
<input id="title" name="title" type="text" value="{{ $project->title }}" size="100"/>
<br><br>

<label for="slug">Slug</label><br>
<input id="slug" name="slug" type="text" value="{{ $project->slug }}" size="100"/>
<br><br>

<label for="md_body">Summary</label><br>
<textarea cols="80" id="md_body" name="md_body" rows="20">{{ $project->md_body }}</textarea>
<br><br>

<label for="image">Image</label><br>
<input id="image" name="image" type="text" value="{{ $project->image }}" size="100"/>
<br><br>

resources/views/admin/projects/edit.blade.php
@extends('layouts.admin')

@section('title', $project->title)

@section('content')
	<form method="POST" action="{{ route('admin.projects.update', $project) }}" enctype="multipart/form-data">
		{{ method_field('PUT') }}

		@include('admin.projects._fields')

		<button type="submit">Update</button>
	</form>
@endsection

resources/views/admin/projects/index.blade.php
@extends('layouts.admin')

@section('title', 'Projects')

@section('content')
	<table>
		<colgroup>
			<col class="title"/>
			<col class="manage"/>
		</colgroup>

		<thead>
			<tr>
				<th>Title</th>
				<th>Manage</th>
			</tr>
		</thead>

		<tbody>
			@foreach($projects as $project)
				<tr>
					<td>{{ $project->title }}</td>
					<td>
						<a href="{{ route('admin.projects.edit', $project) }}">Edit</a>
					</td>
				</tr>
			@endforeach
		</tbody>
	</table>
@endsection