routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Post;


Route::get('', function () {
    $posts = Post::where('published', true)->orderBy('created_at', 'desc')->limit(3)->get();
    return view('index', compact('posts'));
});

Route::resource('projects', 'ProjectsController', ['only' => [
    'index', 'show'
]]);

Route::resource('blog', 'PostsController', ['only' => [
    'index', 'show'
]]);

Route::get('japanese', function() {
    $data = [];
    if (Storage::exists('wanikani.json')) {
        $contents = Storage::get('wanikani.json');
        $data = json_decode($contents);
    }
    return view('japanese', compact('data'));
});

Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'as' => 'admin.', 'middleware' => 'auth'], function() {
    Route::get('', 'HomeController@index');
    Route::resource('projects', 'ProjectsController');
    Route::resource('posts', 'PostsController');
});

Auth::routes();

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{

    public $fillable = [
        'title',
        'slug',
        'md_body',
        'published',
    ];

}

app/Http/Controllers/Admin/PostsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Post;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use GrahamCampbell\Markdown\Facades\Markdown;

class PostsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
		$posts = Post::orderBy('created_at', 'desc')->get();
		return view('admin.posts.index', compact('posts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
		$post = new Post;
		return view('admin.posts.create', compact('post'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
		$post = Post::create(request([
			'title',
			'slug',
			'md_body',
            'published',
		]));

        $post->body = Markdown::convertToHtml($post->md_body);
		$post->save();

		return redirect(route('admin.posts.index'));
	}

    /**
     * Display the specified resource.
     *
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function show(Post $post)
    {
		return redirect(route('admin.posts.edit'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function edit(Post $post)
    {
		return view('admin.posts.edit', compact('post'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Post $post)
    {
		$post->update(request([
			'title',
			'slug',
			'md_body',
            'published',
		]));

        $post->body = Markdown::convertToHtml($post->md_body);
		$post->save();

		return redirect(route('admin.posts.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function destroy(Post $post)
    {
		$post->delete();
		return redirect(route('admin.posts.index'));
    }
}

app/Http/Controllers/PostsController.php
<?php

namespace App\Http\Controllers;

use App\Post;
use Illuminate\Http\Request;

class PostsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
		$posts = Post::where('published', true)->orderBy('created_at', 'desc')->get();
		return view('posts.index', compact('posts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function show($slug)
    {
		$post = Post::where('slug', $slug)->where('published', true)->first();

		if ($post) {
			return view('posts.show', compact('post'));
		} else {
            abort(404);
		}
	}

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function edit(Post $post)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Post $post)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function destroy(Post $post)
    {
        //
    }
}

resources/views/admin/posts/_fields.blade.php
{{ csrf_field() }}

<label for="title">Title</label><br>
<input name="title" id="title" type="text" value="{{ $post->title }}"/>
<br><br>

<label for="slug">Slug</label><br>
<input name="slug" id="slug" type="text" value="{{ $post->slug }}"/>
<br><br>

<label for="title">Title</label><br>
<textarea id="md_body" cols="80" id="md_body" name="md_body" rows="20">{{ $post->md_body }}</textarea>
<br><br>

<label><input name="published" type="checkbox" value="true" {{ $post->published?'checked="checked"':'' }}/>Published</label>
<br><br>

resources/views/admin/posts/create.blade.php
@extends('layouts.admin')

@section('title', 'New Blog Post')

@section('content')
	<form method="POST" action="{{ route('admin.posts.store') }}">

		@include('admin.posts._fields')

		<button type="submit">Create Post</button>
	</form>
@endsection

resources/views/admin/posts/edit.blade.php
@extends('layouts.admin')

@section('title', $post->title)

@section('content')
	<form method="POST" action="{{ route('admin.posts.update', $post) }}">
		{{ method_field('PUT') }}

		@include('admin.posts._fields')

		<button type="submit">Update Post</button>
	</form>
@endsection

resources/views/admin/posts/index.blade.php
@extends('layouts.admin')

@section('title', 'Posts')

@section('content')
	<a href="{{ route('admin.posts.create') }}">New Blog Post</a>

	<table>
		<colgroup>
			<col class="title"/>
			<col class="date"/>
			<col class="manage"/>
		</colgroup>

		<thead>
			<tr>
				<th>Title</th>
				<th>Date</th>
				<th>Manage</th>
			</tr>
		</thead>

		<tbody>
			@foreach($posts as $post)
				<tr>
					<td>{{ $post->title }}</td>
					<td>{{ $post->created_at }}</td>
					<td>
						<a href="{{ route('admin.posts.edit', $post) }}">Edit</a>
					</td>
				</tr>
			@endforeach
		</tbody>
	</table>
@endsection