routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Post;


Route::get('', function () {
    $posts = Post::where('published', true)->orderBy('created_at', 'desc')->limit(3)->get();
    return view('index', compact('posts'));
});

Route::resource('projects', 'ProjectsController', ['only' => [
    'index', 'show'
]]);

Route::resource('blog', 'PostsController', ['only' => [
    'index', 'show'
]]);

Route::get('japanese', function() {
    $data = [];
    if (Storage::exists('wanikani.json')) {
        $contents = Storage::get('wanikani.json');
        $data = json_decode($contents);
    }
    return view('japanese', compact('data'));
});

Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'as' => 'admin.', 'middleware' => 'auth'], function() {
    Route::get('', 'HomeController@index');
    Route::resource('projects', 'ProjectsController');
    Route::resource('posts', 'PostsController');
});

Auth::routes();

resources/views/layouts/admin.blade.php
<!doctype html>
<html lang="en">
    <head>
        <meta charset="UTF-8"/>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>@yield('title') | suchprogrammer.net admin</title>

		<link href="{{ asset('css/admin.css') }}" rel="stylesheet"/>
    </head>
    <body>
		<section class="hero">
			<div class="hero-body">
				<div class="container">
					<h1 class="title">@yield('title')</h1>
				</div>
			</div>
		</section>

		<ul>
			<li>
				<form method="POST" action="{{ route('logout') }}">
					{{ csrf_field() }}
					<button type="submit">Logout</button>
				</form>
			</li>

			<li>
				<a href="{{ route('admin.projects.index') }}">Projects</a>
			</li>

			<li>
				<a href="{{ route('admin.posts.index') }}">Blog Posts</a>
			</li>
		</ul>

		@yield('content')

		<script src="{{ asset('js/admin.js') }}"></script>
		@yield('js')
    </body>
</html>

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ config('app.locale') }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="{{ mix('css/app.css') }}" rel="stylesheet">

    <!-- Scripts -->
    <script>
        window.Laravel = {!! json_encode([
            'csrfToken' => csrf_token(),
        ]) !!};
    </script>
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Branding Image -->
                    <a class="navbar-brand" href="{{ url('/') }}">
                        {{ config('app.name', 'Laravel') }}
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <ul class="nav navbar-nav">
                        &nbsp;
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-right">
                        <!-- Authentication Links -->
                        @if (Auth::guest())
                            <li><a href="{{ route('login') }}">Login</a></li>
                        @else
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <ul class="dropdown-menu" role="menu">
                                    <li>
                                        <a href="{{ route('logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            Logout
                                        </a>

                                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                                </ul>
                            </li>
                        @endif
                    </ul>
                </div>
            </div>
        </nav>

        @yield('content')
    </div>

    <!-- Scripts -->
    <script src="{{ mix('js/app.js') }}"></script>
</body>
</html>

resources/views/layouts/front.blade.php
<!doctype html>
<html lang="en">
	<head>
		<meta charset="UTF-8"/>
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>@yield('title') | suchprogrammer.net </title>

		<!-- Favicon city -->
		<link rel="apple-touch-icon" sizes="152x152" href="{{ asset('/favicon/apple-touch-icon.png') }}">
		<link rel="icon" type="image/png" href="{{ asset('/favicon/favicon-32x32.png') }}" sizes="32x32">
		<link rel="icon" type="image/png" href="{{ asset('/favicon/favicon-16x16.png') }}" sizes="16x16">
		<link rel="manifest" href="{{ asset('/favicon/manifest.json') }}">
		<link rel="mask-icon" href="{{ asset('/favicon/safari-pinned-tab.svg') }}" color="#5bbad5">
		<link rel="shortcut icon" href="{{ asset('/favicon/favicon.ico') }}">
		<meta name="msapplication-config" content="{{ asset('/favicon/browserconfig.xml') }}">
		<meta name="theme-color" content="#ffffff">

		<link href="{{ asset('css/app.css') }}" rel="stylesheet"/>
	</head>
	<body>
		@include('shared.nav')

		@yield('content')

		@include('shared.footer')

		<script src="/js/analytics.js" async defer></script>
		<script src="{{ asset('js/app.js') }}" type="text/javascript" async></script>
		@yield('js')
	</body>
</html>